// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Woy1Cj1mUV6ZqOP0zgkAUXUdW358HLA',
    appId: '1:785455981664:web:bc3339ec145500e5a2cf05',
    messagingSenderId: '785455981664',
    projectId: 'envite-canario',
    authDomain: 'envite-canario.firebaseapp.com',
    storageBucket: 'envite-canario.firebasestorage.app',
    measurementId: 'G-7CT7H5EDGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrGfLq4DgIhY2CL0R2a-yMznfAHrWQbEQ',
    appId: '1:785455981664:android:e80567ecf8128c5ea2cf05',
    messagingSenderId: '785455981664',
    projectId: 'envite-canario',
    storageBucket: 'envite-canario.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHNodEvQ50A-exjneWHUxZC7BkKAvOoBk',
    appId: '1:785455981664:ios:d8469a4b98235a55a2cf05',
    messagingSenderId: '785455981664',
    projectId: 'envite-canario',
    storageBucket: 'envite-canario.firebasestorage.app',
    iosBundleId: 'com.example.enviteCanario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHNodEvQ50A-exjneWHUxZC7BkKAvOoBk',
    appId: '1:785455981664:ios:d8469a4b98235a55a2cf05',
    messagingSenderId: '785455981664',
    projectId: 'envite-canario',
    storageBucket: 'envite-canario.firebasestorage.app',
    iosBundleId: 'com.example.enviteCanario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Woy1Cj1mUV6ZqOP0zgkAUXUdW358HLA',
    appId: '1:785455981664:web:a50e46f6aab39010a2cf05',
    messagingSenderId: '785455981664',
    projectId: 'envite-canario',
    authDomain: 'envite-canario.firebaseapp.com',
    storageBucket: 'envite-canario.firebasestorage.app',
    measurementId: 'G-76FX13TNRG',
  );
}
